cmake_minimum_required(VERSION 3.28)

macro(set_variables_from_config content file)
    string(REPLACE "\n" ";" lines "${content}")
    foreach(line ${lines})
        if(line MATCHES "^([A-Za-z_]+)[ ]*[+]*=[ ]*(.*)$")
            set(key "${CMAKE_MATCH_1}")
            set(value "${CMAKE_MATCH_2}")
            string(STRIP "${value}" value)
            message(STATUS "Force new variable definition: ${key}=${value}")
            string(FIND "${key}" "PATH" SUBSTRING_POSITION)
            if(SUBSTRING_POSITION GREATER -1)
                string(REGEX REPLACE "^\"|\"$" "" VALUE_CLEANED "${value}")
                set(${key} "${VALUE_CLEANED}" CACHE FILEPATH "Value for ${key} as defined in ${file}" FORCE)
            else()
                set(${key} "${value}" CACHE STRING "Value for ${key} as defined in ${file}" FORCE)
            endif()
        endif()
    endforeach()
endmacro()

macro(load_key_value_file file)
    if(NOT EXISTS ${file})
        message(FATAL_ERROR "File not found: ${file}")
    endif()
    file(READ ${file} content)
    set_variables_from_config("${content}" "${file}")
endmacro()
